project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notation.qmd

filters:
  - status-callout.lua

format:
  html:
    css: styles.css
    notebook-links: false
    notebook-view: false
    comments:
      hypothesis: true
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            chtml: {
              matchFontHeight: false
            },
            svg: {
              matchFontHeight: false
            }
          };
          </script>
  docx: default
  jats: default
  pdf: default

execute:
  freeze: true
